'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { HeardSomething, PaperFooter, PaperHeader } from '@/components/publication-brand';
import type { EditionArticle } from '@/lib/edition-types';
type ReaderEdition = { id: string; number: number; date: string; title: string; preview: string; withdrawnCount: number; articles: (Pick<EditionArticle, 'publicationId' | 'headline' | 'byline'> & Partial<EditionArticle>)[] };
const dateLabel = (date: string) => new Date(`${date}T12:00:00Z`).toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Australia/Sydney' });
export default function EditionReader({ id }: { id: string }) {
  const [result, setResult] = useState<{ edition: ReaderEdition; entitled: boolean }>();
  const [error, setError] = useState('');
  useEffect(() => {
    const controller = new AbortController();
    fetch(`/api/editions/${encodeURIComponent(id)}`, { cache: 'no-store', signal: controller.signal }).then(async response => { const value = await response.json(); if (!response.ok) throw new Error(value.error || 'The edition could not be opened.'); return value; }).then(setResult).catch(reason => { if (reason.name !== 'AbortError') setError(reason.message); });
    return () => controller.abort();
  }, [id]);
  const edition = result?.edition;
  return <main className="paper reader-paper"><PaperHeader /><div className="paper-dateline"><Link href="/editions">← EDITION ARCHIVE</Link><span>{edition ? `NO. ${edition.number} · ${dateLabel(edition.date)}` : 'THE THURSDAY EDITION'}</span><Link href="/member">Your account ↗</Link></div>
    {error ? <section className="paper-message"><h1>Edition unavailable</h1><p role="alert">{error}</p><Link href="/editions">Browse the edition archive</Link></section> : !edition || !result ? <p className="paper-message" role="status">Opening the edition…</p> : <>
      <header className="reader-heading reader-edition-heading"><p className="paper-kicker">THE THURSDAY EDITION · NO. {edition.number}</p><h1>{edition.title}</h1><p>{edition.preview}</p>{edition.withdrawnCount > 0 ? <aside className="paper-correction"><strong>Editorial notice</strong><p>{edition.withdrawnCount} {edition.withdrawnCount === 1 ? 'article has' : 'articles have'} been withdrawn following editorial review.</p><Link href="/corrections">Corrections &amp; updates ↗</Link></aside> : null}</header>
      <div className="reader-edition-layout"><div>{result.entitled ? <><div className="reader-toolbar"><span className="paper-kicker">THE COMPLETE EDITION</span><button className="paper-button reader-button-outline" onClick={() => window.print()}>Print or save as PDF</button></div>{edition.articles.map((article, index) => <article className="reader-edition-story" id={`story-${article.publicationId}`} key={article.publicationId}><p className="paper-kicker">{String(index + 1).padStart(2, '0')} / THE THURSDAY POST</p><h2>{article.headline}</h2><div className="paper-byline">By {article.byline.replace(/^By\s+/i, '')}<span> / </span><time dateTime={edition.date}>{dateLabel(edition.date)}</time></div><div className="paper-body">{article.paragraphs?.map((paragraph, paragraphIndex) => <p key={paragraphIndex}>{paragraph}</p>)}</div>{article.limitations?.length ? <aside className="paper-reporting"><h3>Editorial notes</h3>{article.limitations.map((note, noteIndex) => <p key={noteIndex}>{note}</p>)}</aside> : null}{article.sources?.length ? <aside className="paper-reporting"><h3>Sources &amp; further reading</h3>{article.sources.map((source, sourceIndex) => <a key={sourceIndex} href={source.url} target="_blank" rel="noopener noreferrer">{source.title} ↗</a>)}</aside> : null}</article>)}</> : <section className="paper-paywall reader-edition-paywall"><p className="paper-kicker">CONTINUE WITH THURSDAY POST</p><h2>The complete paper.<br />A considered Thursday.</h2><p>This edition is for subscribers. Sign in to read the full reporting and its sources.</p><Link className="paper-button" href="/member">Subscriber sign in ↗</Link><Link href="/subscribe">See the subscription</Link></section>}</div>
      <aside className="reader-margin reader-contents"><p className="paper-column-label">IN THIS EDITION</p><ol>{edition.articles.map((article, index) => <li key={article.publicationId}><span className="reader-contents-number">{String(index + 1).padStart(2, '0')}</span><div><h3>{result.entitled ? <a href={`#story-${article.publicationId}`}>{article.headline}</a> : article.headline}</h3><p className="paper-byline">By {article.byline.replace(/^By\s+/i, '')}</p></div></li>)}</ol>{!edition.articles.length ? <p>No articles remain available in this edition.</p> : null}<div className="paper-rule" /><Link className="paper-continue" href="/editions">Browse past editions ↗</Link></aside></div>
    </>}
    <HeardSomething /><PaperFooter /></main>;
}
