import { createHash } from 'node:crypto';
import type { LicensedImage, Publication } from './domain';
import { imageRightsCleared, normaliseLicenceCode } from './image-rights';

/**
 * The picture desk looks for openly licensed photographs of the story's own subjects: the horse,
 * the people, the racecourse. It never scrapes publisher images and never accepts a generic picture:
 * a candidate must name the matched subject in its own title or description, carry an open licence,
 * and not be AI-generated, a logo or a diagram. Only metadata is stored; the file stays at its host.
 */

const COMMONS_API = 'https://commons.wikimedia.org/w/api.php';
const USER_AGENT = 'ThursdayPostPictureDesk/1.0 (https://the-racing-desk.vercel.app; workbenchadmin@gmail.com)';
const MAX_IMAGES_PER_STORY = 2;
const MAX_TERMS = 4;
const MIN_WIDTH = 800;

const RACING_WORDS = /\b(horses?|racehorses?|racing|races?|raced|jockeys?|trainers?|racecourses?|race ?courses?|turf|stakes|cups?|thoroughbreds?|mounting yard|geldings?|mares?|colts?|fill(?:y|ies)|stallions?|studs?|derby|oaks|plate|handicap|meetings?|carnivals?)\b/i;
/** A venue picture must show the racecourse, not a station, a statue of some other horse or a sign. */
const NOT_A_VENUE_PICTURE = /\b(railway|station|train|tram|bus|statue|sculpture|memorial|plaque|sign|signage|map|aerial view of the city)\b/i;
/** Catalogue records from museum uploads are not captions. */
const CATALOGUE_TEXT = /\b(format|rights info|repository|accession|call number|identifier|glass plate negative)\s*:/i;
const VENUE_WORDS = /\b(racecourse|race ?course|racetrack|race track|turf club|racing club|jockey club|grandstand|mounting yard|straight|home turn|track)\b/i;
const REJECT_TITLE = /\b(logo|map|diagram|chart|coat of arms|flag|icon|seal|signature|poster|screenshot)\b/i;
const AI_GENERATED = /(ai[- ]generated|midjourney|stable diffusion|dall[- ]?e|generative ai|image generated by)/i;

/** Well-known Australian racecourses: a named venue is a legitimate, story-specific picture. */
const VENUES = ['Flemington', 'Randwick', 'Rosehill', 'Caulfield', 'Moonee Valley', 'Eagle Farm', 'Doomben', 'Morphettville', 'Ascot', 'Warwick Farm', 'Canterbury Park', 'Kembla Grange', 'Newcastle', 'Gosford', 'Wyong', 'Hawkesbury', 'Scone', 'Muswellbrook', 'Tamworth', 'Grafton', 'Coffs Harbour', 'Port Macquarie', 'Taree', 'Ballina', 'Lismore', 'Toowoomba', 'Gold Coast', 'Sunshine Coast', 'Ipswich', 'Townsville', 'Rockhampton', 'Cairns', 'Mackay', 'Bendigo', 'Ballarat', 'Geelong', 'Pakenham', 'Sandown', 'Cranbourne', 'Mornington', 'Warrnambool', 'Kilmore', 'Wagga Wagga', 'Albury', 'Canberra', 'Launceston', 'Hobart', 'Birdsville', 'Bathurst', 'Dubbo', 'Mudgee', 'Orange', 'Goulburn', 'Nowra', 'Moruya', 'Hanging Rock', 'Echuca', 'Swan Hill', 'Mildura', 'Hamilton', 'Casterton', 'Oakbank', 'Gawler', 'Murray Bridge', 'Belmont Park', 'Pinjarra', 'Bunbury', 'Kalgoorlie', 'Broome', 'Darwin', 'Alice Springs'];
const NOT_SUBJECTS = new Set(['Racing NSW', 'Racing Queensland', 'Racing Victoria', 'Racing Australia', 'Racing SA', 'Racing WA', 'Racing Tasmania', 'Thursday Post', 'The Thursday Post', 'Australian Turf Club', 'Victoria Racing Club', 'Melbourne Racing Club', 'Brisbane Racing Club', 'New South Wales', 'Queensland', 'Victoria', 'South Australia', 'Western Australia', 'Northern Territory', 'Australia', 'Sydney', 'Melbourne', 'Brisbane', 'Adelaide', 'Perth', 'Agent', 'The', 'He', 'She', 'They', 'It', 'In', 'On', 'At', 'But', 'And', 'A', 'An', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']);

export interface PictureTerm { term: string; kind: 'subject' | 'venue'; weight: number }

/** Named horses, people and racecourses in the approved text, most prominent first. */
export function pictureTerms(text: { headline: string; paragraphs: string[] }): PictureTerm[] {
  const body = [text.headline, ...text.paragraphs].join('\n');
  const found = new Map<string, PictureTerm>();
  const bump = (term: string, kind: PictureTerm['kind'], weight: number) => {
    const current = found.get(term);
    if (current) current.weight += weight; else found.set(term, { term, kind, weight });
  };
  for (const venue of VENUES) {
    const hits = body.match(new RegExp(`\\b${venue.replace(/ /g, '\\s+')}\\b`, 'g'))?.length ?? 0;
    if (hits) bump(venue, 'venue', hits + (text.headline.includes(venue) ? 2 : 0));
  }
  // Capitalised runs of two to four words: "Wild Monarch", "Jenny Graham", "Daniel Smith".
  for (const match of body.matchAll(/\b([A-Z][a-z'’]+(?:\s+(?:[A-Z][a-z'’]+|Mc[A-Z][a-z]+|O'[A-Z][a-z]+|de|van|der|Van|Der)){1,3})\b/g)) {
    const term = match[1].replace(/[’']s$/, '').trim();
    const first = term.split(/\s+/)[0];
    if (NOT_SUBJECTS.has(term) || NOT_SUBJECTS.has(first) || VENUES.includes(term)) continue;
    if (/^(Racing|Agent|Race|Group|Listed)\b/.test(term)) continue;
    bump(term, 'subject', text.headline.includes(term) ? 3 : 1);
  }
  return [...found.values()].sort((a, b) => b.weight - a.weight || (a.kind === 'subject' ? -1 : 1)).slice(0, MAX_TERMS);
}

export function commonsSearchUrl(term: PictureTerm): string {
  const query = term.kind === 'venue' ? `"${term.term}" racecourse` : `"${term.term}" (horse OR racing OR jockey OR trainer OR racecourse)`;
  const params = new URLSearchParams({
    action: 'query', format: 'json', formatversion: '2', origin: '*',
    generator: 'search', gsrnamespace: '6', gsrlimit: '10', gsrsearch: `${query} filetype:bitmap`,
    prop: 'imageinfo', iiprop: 'url|size|mime|extmetadata', iiurlwidth: '1600',
    iiextmetadatafilter: 'ImageDescription|Artist|Credit|LicenseShortName|LicenseUrl|License|DateTimeOriginal|Categories|NonFree|ObjectName',
  });
  return `${COMMONS_API}?${params}`;
}

const stripHtml = (value: unknown) => typeof value === 'string' ? value.replace(/<[^>]*>/g, ' ').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#0?39;/g, "'").replace(/\s+/g, ' ').trim() : '';
const meta = (extmetadata: Record<string, { value?: unknown }> | undefined, key: string) => stripHtml(extmetadata?.[key]?.value);
const titleText = (title: string) => title.replace(/^File:/, '').replace(/\.[a-z0-9]{2,4}$/i, '').replace(/[_]+/g, ' ').trim();
const containsTerm = (haystack: string, term: string) => new RegExp(`\\b${term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/g, '\\s+')}\\b`, 'i').test(haystack);

interface CommonsPage { title?: string; index?: number; imageinfo?: { url?: string; thumburl?: string; thumbwidth?: number; thumbheight?: number; width?: number; height?: number; mime?: string; descriptionurl?: string; extmetadata?: Record<string, { value?: unknown }> }[] }

/** Turn one Commons search response into pictures that are cleared to print for this term. */
export function commonsCandidates(response: unknown, term: PictureTerm, addedAt: string): LicensedImage[] {
  const pages = ((response as { query?: { pages?: CommonsPage[] } })?.query?.pages ?? []).slice().sort((a, b) => (a.index ?? 0) - (b.index ?? 0));
  const images: LicensedImage[] = [];
  for (const page of pages) {
    const info = page.imageinfo?.[0];
    if (!page.title || !info?.descriptionurl) continue;
    const extmetadata = info.extmetadata;
    const title = titleText(page.title);
    const description = meta(extmetadata, 'ImageDescription') || meta(extmetadata, 'ObjectName');
    const categories = meta(extmetadata, 'Categories');
    const haystack = `${title} ${description}`;
    if (!/^image\/(jpeg|webp)$/.test(info.mime ?? '')) continue;
    if ((info.width ?? 0) < MIN_WIDTH) continue;
    if (meta(extmetadata, 'NonFree').toLowerCase() === 'true') continue;
    if (REJECT_TITLE.test(title) || AI_GENERATED.test(`${haystack} ${categories}`)) continue;
    if (!containsTerm(haystack, term.term)) continue;
    if (term.kind === 'subject' && !RACING_WORDS.test(`${haystack} ${categories}`)) continue;
    if (term.kind === 'venue' && !VENUE_WORDS.test(`${haystack} ${categories}`) && !RACING_WORDS.test(`${haystack} ${categories}`)) continue;
    if (term.kind === 'venue' && NOT_A_VENUE_PICTURE.test(haystack)) continue;
    const code = normaliseLicenceCode(meta(extmetadata, 'License') || meta(extmetadata, 'LicenseShortName'));
    const credit = (meta(extmetadata, 'Artist') || meta(extmetadata, 'Credit')).slice(0, 200);
    if (!credit) continue;
    const url = info.thumburl ?? info.url;
    const width = info.thumburl ? info.thumbwidth : info.width;
    const height = info.thumburl ? info.thumbheight : info.height;
    if (!url || !width || !height) continue;
    const taken = meta(extmetadata, 'DateTimeOriginal').match(/\b(1[89]|20)\d{2}\b/)?.[0];
    // Wiki link prefixes ("w:") and museum catalogue records are cleaned out; the file title stands in when needed.
    const cleaned = description.replace(/\bw:/g, '').replace(/\s+([,.;])/g, '$1');
    const firstSentence = cleaned.split(/(?<=\.)\s/)[0] ?? '';
    const shows = (CATALOGUE_TEXT.test(cleaned) || firstSentence.length < 12 ? title : firstSentence).slice(0, 280).replace(/\.$/, '');
    const image: LicensedImage = {
      id: `commons-${createHash('sha256').update(info.descriptionurl).digest('hex').slice(0, 20)}`,
      url, width, height,
      alt: shows.slice(0, 280),
      caption: taken && !shows.includes(taken) ? `${shows} (${taken}).` : `${shows}.`,
      credit,
      licence: { code, name: meta(extmetadata, 'LicenseShortName') || code, ...(meta(extmetadata, 'LicenseUrl').startsWith('http') ? { url: meta(extmetadata, 'LicenseUrl') } : {}) },
      origin: 'wikimedia_commons',
      sourcePage: info.descriptionurl,
      relevance: term.kind === 'venue' ? 'venue' : 'subject',
      matchedTerm: term.term,
      addedAt, addedBy: 'picture-desk',
    };
    if (imageRightsCleared(image)) images.push(image);
  }
  return images;
}

export type PictureFetch = (url: string, init: RequestInit) => Promise<Response>;

/** Search for up to two cleared pictures of this story's own subjects; subjects before venues. */
export async function findLicensedImages(article: { headline: string; paragraphs: string[] }, options: { fetch?: PictureFetch; deadline?: number; now?: string; terms?: PictureTerm[] } = {}): Promise<LicensedImage[]> {
  const request = options.fetch ?? fetch;
  const addedAt = options.now ?? new Date().toISOString();
  const chosen: LicensedImage[] = [];
  for (const term of options.terms ?? pictureTerms(article)) {
    if (chosen.length >= MAX_IMAGES_PER_STORY) break;
    if (options.deadline && Date.now() > options.deadline - 3_000) break;
    try {
      const response = await request(commonsSearchUrl(term), { headers: { 'User-Agent': USER_AGENT, Accept: 'application/json' }, signal: AbortSignal.timeout(8_000), redirect: 'error', cache: 'no-store' });
      if (!response.ok) continue;
      for (const image of commonsCandidates(await response.json(), term, addedAt)) {
        if (chosen.length >= MAX_IMAGES_PER_STORY) break;
        if (!chosen.some(item => item.id === image.id)) chosen.push(image);
      }
    } catch { /* A failed lookup leaves the story on its typographic treatment. */ }
  }
  return chosen;
}

/** Keep James's own choices; add the desk's finds without duplicates, within the per-story limit. */
export function mergeImages(existing: LicensedImage[] | undefined, found: LicensedImage[]): LicensedImage[] {
  const merged = [...(existing ?? [])];
  for (const image of found) if (!merged.some(item => item.id === image.id) && merged.length < MAX_IMAGES_PER_STORY + 2) merged.push(image);
  return merged;
}

/** Stories the desk has not yet looked at, newest first. */
export function picturesPending(publications: Publication[], limit: number): Publication[] {
  return publications.filter(publication => publication.mode === 'live' && publication.public && publication.status !== 'removed' && publication.status !== 'retracted' && !publication.picturesCheckedAt)
    .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt)).slice(0, limit);
}
