import { createHash } from 'node:crypto';
import type { LicensedImage, Publication } from './domain';
import { imageRightsCleared, imageRightsProblem, normaliseLicenceCode } from './image-rights';

/**
 * The picture desk looks for openly licensed photographs of the story's own subjects: the horse,
 * the people, the racecourse. It never scrapes publisher images and never accepts a generic picture:
 * a candidate must name the matched subject in its own title or description, carry an open licence,
 * and not be AI-generated, a logo or a diagram. Only metadata is stored; the file stays at its host.
 */

const COMMONS_API = 'https://commons.wikimedia.org/w/api.php';
const USER_AGENT = 'ThursdayPostPictureDesk/1.0 (https://the-racing-desk.vercel.app; workbenchadmin@gmail.com)';
const MAX_IMAGES_PER_STORY = 2;
const MAX_TERMS = 4;
const MIN_WIDTH = 800;
const MIN_SUBJECT_WIDTH = 640;

/** Unambiguous racing words. Weak words (cup, plate, stud, meeting) matched a 1940 radio station called WINX. */
const RACING_WORDS = /\b(horses?|racehorses?|horse racing|racing|races?|raced|jockeys?|trainers? of racehorses|racecourses?|race ?courses?|thoroughbreds?|geldings?|mares?|colts?|fill(?:y|ies)|stallions?|derby|mounting yard|Melbourne Cup|Caulfield Cup|Cox Plate|Golden Slipper|Group 1)\b/i;
/** A venue picture must show the racecourse, not a station, a statue of some other horse or a sign. */
const NOT_A_VENUE_PICTURE = /\b(railway|station|train|tram|bus|statue|sculpture|memorial|plaque|sign|signage|map|car ?park|underpass|aerial view of the city)\b/i;
/** Several racecourse names exist abroad (Scone and Perth in Scotland, Ascot in England). */
const AUSTRALIAN_PLACE = /(?<![A-Za-z])(Australia|Australian|New South Wales|NSW|N\.S\.W\.|Victoria|Queensland|Qld|South Australia|Western Australia|Tasmania|Northern Territory|Sydney|Melbourne|Brisbane|Adelaide|Hobart|Darwin|Canberra|Hunter Region|Upper Hunter|Mid North Coast|Northern Rivers|Gold Coast|Sunshine Coast|outback)(?![A-Za-z])/i;
/** Catalogue records from museum uploads are not captions. */
const CATALOGUE_TEXT = /\b(format|rights info|repository|accession|call number|identifier|glass plate negative)\s*:/i;
const VENUE_WORDS = /\b(racecourse|race ?course|racetrack|race track|turf club|racing club|jockey club|grandstand|mounting yard|straight|home turn|track)\b/i;
const REJECT_TITLE = /\b(logo|map|diagram|chart|coat of arms|flag|icon|seal|signature|poster|screenshot)\b/i;
const AI_GENERATED = /(ai[- ]generated|midjourney|stable diffusion|dall[- ]?e|generative ai|image generated by)/i;

/** Well-known Australian racecourses: a named venue is a legitimate, story-specific picture. */
const VENUES = ['Flemington', 'Randwick', 'Rosehill', 'Caulfield', 'Moonee Valley', 'Eagle Farm', 'Doomben', 'Morphettville', 'Ascot', 'Warwick Farm', 'Canterbury Park', 'Kembla Grange', 'Newcastle', 'Gosford', 'Wyong', 'Hawkesbury', 'Scone', 'Muswellbrook', 'Tamworth', 'Grafton', 'Coffs Harbour', 'Port Macquarie', 'Taree', 'Ballina', 'Lismore', 'Toowoomba', 'Gold Coast', 'Sunshine Coast', 'Ipswich', 'Townsville', 'Rockhampton', 'Cairns', 'Mackay', 'Bendigo', 'Ballarat', 'Geelong', 'Pakenham', 'Sandown', 'Cranbourne', 'Mornington', 'Warrnambool', 'Kilmore', 'Wagga Wagga', 'Albury', 'Canberra', 'Launceston', 'Hobart', 'Birdsville', 'Bathurst', 'Dubbo', 'Mudgee', 'Orange', 'Goulburn', 'Nowra', 'Moruya', 'Hanging Rock', 'Echuca', 'Swan Hill', 'Mildura', 'Hamilton', 'Casterton', 'Oakbank', 'Gawler', 'Murray Bridge', 'Belmont Park', 'Pinjarra', 'Bunbury', 'Kalgoorlie', 'Broome', 'Darwin', 'Alice Springs'];
const NOT_SUBJECTS = new Set(['Racing NSW', 'Racing Queensland', 'Racing Victoria', 'Racing Australia', 'Racing SA', 'Racing WA', 'Racing Tasmania', 'Thursday Post', 'The Thursday Post', 'Australian Turf Club', 'Victoria Racing Club', 'Melbourne Racing Club', 'Brisbane Racing Club', 'New South Wales', 'Queensland', 'Victoria', 'South Australia', 'Western Australia', 'Northern Territory', 'Australia', 'Sydney', 'Melbourne', 'Brisbane', 'Adelaide', 'Perth', 'Agent', 'The', 'He', 'She', 'They', 'It', 'In', 'On', 'At', 'But', 'And', 'A', 'An', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']);

export interface PictureTerm { term: string; kind: 'subject' | 'venue'; weight: number }

/** Named horses, people and racecourses in the approved text, most prominent first. */
export function pictureTerms(text: { headline: string; paragraphs: string[] }): PictureTerm[] {
  const body = [text.headline, ...text.paragraphs].join('\n');
  const found = new Map<string, PictureTerm>();
  const bump = (term: string, kind: PictureTerm['kind'], weight: number) => {
    const current = found.get(term);
    if (current) current.weight += weight; else found.set(term, { term, kind, weight });
  };
  for (const venue of VENUES) {
    const hits = body.match(new RegExp(`\\b${venue.replace(/ /g, '\\s+')}\\b`, 'g'))?.length ?? 0;
    if (hits) bump(venue, 'venue', hits + (text.headline.includes(venue) ? 2 : 0));
  }
  // Capitalised runs of two to four words: "Wild Monarch", "Jenny Graham", "Daniel Smith".
  for (const match of body.matchAll(/\b([A-Z][a-z'’]+(?:\s+(?:[A-Z][a-z'’]+|Mc[A-Z][a-z]+|O'[A-Z][a-z]+|de|van|der|Van|Der)){1,3})\b/g)) {
    const term = match[1].replace(/[’']s$/, '').trim();
    const first = term.split(/\s+/)[0];
    if (NOT_SUBJECTS.has(term) || NOT_SUBJECTS.has(first) || VENUES.includes(term)) continue;
    if (/^(Racing|Agent|Race|Group|Listed)\b/.test(term)) continue;
    bump(term, 'subject', text.headline.includes(term) ? 3 : 1);
  }
  return [...found.values()].sort((a, b) => b.weight - a.weight || (a.kind === 'subject' ? -1 : 1)).slice(0, MAX_TERMS);
}

export function commonsSearchUrl(term: PictureTerm, byCategory: false | 'horse' | 'exact' = false): string {
  const query = byCategory ? (byCategory === 'horse' ? `incategory:"${term.term} (horse)"` : `incategory:"${term.term}"`) : term.kind === 'venue' ? `"${term.term}" racecourse` : `"${term.term}" (horse OR racing OR jockey OR trainer OR racecourse)`;
  const params = new URLSearchParams({
    action: 'query', format: 'json', formatversion: '2', origin: '*',
    generator: 'search', gsrnamespace: '6', gsrlimit: '10', gsrsearch: `${query} filetype:bitmap`,
    prop: 'imageinfo', iiprop: 'url|size|mime|extmetadata', iiurlwidth: '1600',
    iiextmetadatafilter: 'ImageDescription|Artist|Credit|LicenseShortName|LicenseUrl|License|DateTimeOriginal|Categories|NonFree|ObjectName',
  });
  return `${COMMONS_API}?${params}`;
}

const stripHtml = (value: unknown) => typeof value === 'string' ? value.replace(/<[^>]*>/g, ' ').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#0?39;/g, "'").replace(/\s+/g, ' ').trim() : '';
const meta = (extmetadata: Record<string, { value?: unknown }> | undefined, key: string) => stripHtml(extmetadata?.[key]?.value);
// Flickr and archive upload numbers in brackets are not part of what the picture shows.
const titleText = (title: string) => title.replace(/^File:/, '').replace(/\.[a-z0-9]{2,4}$/i, '').replace(/[_]+/g, ' ').replace(/\s*\(\d{6,}\)/g, '').trim();
const containsTerm = (haystack: string, term: string) => new RegExp(`\\b${term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/g, '\\s+')}\\b`, 'i').test(haystack);

interface CommonsPage { title?: string; index?: number; imageinfo?: { url?: string; thumburl?: string; thumbwidth?: number; thumbheight?: number; width?: number; height?: number; mime?: string; descriptionurl?: string; extmetadata?: Record<string, { value?: unknown }> }[] }

/** Turn one Commons search response into pictures that are cleared to print for this term. */
export function commonsCandidates(response: unknown, term: PictureTerm, addedAt: string, log?: string[]): LicensedImage[] {
  const pages = ((response as { query?: { pages?: CommonsPage[] } })?.query?.pages ?? []).slice().sort((a, b) => (a.index ?? 0) - (b.index ?? 0));
  const images: LicensedImage[] = [];
  for (const page of pages) {
    const info = page.imageinfo?.[0];
    const reject = (reason: string) => { log?.push(`  ✗ ${page.title ?? 'untitled'}: ${reason}`); };
    if (!page.title || !info?.descriptionurl) { reject('no file information'); continue; }
    const extmetadata = info.extmetadata;
    const title = titleText(page.title);
    const description = meta(extmetadata, 'ImageDescription') || meta(extmetadata, 'ObjectName');
    const categories = meta(extmetadata, 'Categories');
    const haystack = `${title} ${description}`;
    if (!/^image\/(jpeg|webp)$/.test(info.mime ?? '')) { reject(`not a photograph (${info.mime})`); continue; }
    // Historic photographs of a subject are often small scans; a venue has plenty of modern ones.
    if ((info.width ?? 0) < (term.kind === 'subject' ? MIN_SUBJECT_WIDTH : MIN_WIDTH)) { reject(`too small (${info.width}px)`); continue; }
    if (meta(extmetadata, 'NonFree').toLowerCase() === 'true') { reject('non-free'); continue; }
    if (REJECT_TITLE.test(title) || AI_GENERATED.test(`${haystack} ${categories}`)) { reject('logo, diagram or AI-generated'); continue; }
    if (!containsTerm(haystack, term.term)) { reject('does not name the subject'); continue; }
    if (term.kind === 'subject' && !RACING_WORDS.test(`${haystack} ${categories}`)) { reject('not about racing'); continue; }
    if (term.kind === 'venue' && !VENUE_WORDS.test(`${haystack} ${categories}`) && !RACING_WORDS.test(`${haystack} ${categories}`)) { reject('not the racecourse'); continue; }
    if (term.kind === 'venue' && NOT_A_VENUE_PICTURE.test(haystack)) { reject('shows a station, statue or sign, not the racecourse'); continue; }
    if (term.kind === 'venue' && !AUSTRALIAN_PLACE.test(`${haystack} ${categories}`)) { reject('not in Australia'); continue; }
    const code = normaliseLicenceCode(meta(extmetadata, 'License') || meta(extmetadata, 'LicenseShortName'));
    const credit = (meta(extmetadata, 'Artist') || meta(extmetadata, 'Credit')).slice(0, 200);
    if (!credit) { reject('no named author'); continue; }
    const url = info.thumburl ?? info.url;
    const width = info.thumburl ? info.thumbwidth : info.width;
    const height = info.thumburl ? info.thumbheight : info.height;
    if (!url || !width || !height) { reject('no usable image size'); continue; }
    // Wiki link prefixes ("w:") and museum catalogue records are cleaned out; the file title stands in when needed.
    const cleaned = description.replace(/\bw:/g, '').replace(/\s+([,.;])/g, '$1');
    const firstSentence = cleaned.split(/(?<=\.)\s/)[0] ?? '';
    const shows = (CATALOGUE_TEXT.test(cleaned) || firstSentence.length < 12 ? title : firstSentence).slice(0, 280).replace(/\.$/, '');
    const image: LicensedImage = {
      id: `commons-${createHash('sha256').update(info.descriptionurl).digest('hex').slice(0, 20)}`,
      url, width, height,
      alt: shows.slice(0, 280),
      // No date is added: upload and scan dates on Commons are often not when the picture was taken.
      caption: `${shows}.`,
      credit,
      licence: { code, name: meta(extmetadata, 'LicenseShortName') || code, ...(meta(extmetadata, 'LicenseUrl').startsWith('http') ? { url: meta(extmetadata, 'LicenseUrl') } : {}) },
      origin: 'wikimedia_commons',
      sourcePage: info.descriptionurl,
      relevance: term.kind === 'venue' ? 'venue' : 'subject',
      matchedTerm: term.term,
      addedAt, addedBy: 'picture-desk',
    };
    if (imageRightsCleared(image)) { images.push(image); log?.push(`  ✓ ${page.title} (${image.licence.name}, ${credit})`); continue; }
    reject(imageRightsProblem(image) ?? 'not cleared');
  }
  return images;
}

export type PictureFetch = (url: string, init: RequestInit) => Promise<Response>;

/** Search for up to two cleared pictures of this story's own subjects; subjects before venues. */
export async function findLicensedImages(article: { headline: string; paragraphs: string[] }, options: { fetch?: PictureFetch; deadline?: number; now?: string; terms?: PictureTerm[]; log?: string[] } = {}): Promise<LicensedImage[]> {
  const request = options.fetch ?? fetch;
  const addedAt = options.now ?? new Date().toISOString();
  const chosen: LicensedImage[] = [];
  for (const term of options.terms ?? pictureTerms(article)) {
    if (chosen.length >= MAX_IMAGES_PER_STORY) break;
    if (options.deadline && Date.now() > options.deadline - 3_000) break;
    try {
      // A subject's Commons category often holds photographs whose descriptions never say "racing".
      // The disambiguated horse category first ("Winx (horse)", not the Winx tower or radio station).
      for (const byCategory of term.kind === 'subject' ? [false, 'horse', 'exact'] as const : [false] as const) {
        if (chosen.length >= MAX_IMAGES_PER_STORY) break;
        const response = await request(commonsSearchUrl(term, byCategory), { headers: { 'User-Agent': USER_AGENT, Accept: 'application/json' }, signal: AbortSignal.timeout(8_000), redirect: 'error', cache: 'no-store' });
        const label = `${term.term} (${term.kind}${byCategory ? `, ${byCategory} category` : ''})`;
        if (!response.ok) { options.log?.push(`${label}: search failed, HTTP ${response.status}`); continue; }
        const body = await response.json();
        options.log?.push(`${label}: ${((body as { query?: { pages?: unknown[] } })?.query?.pages ?? []).length} files returned`);
        for (const image of commonsCandidates(body, term, addedAt, options.log)) {
          if (chosen.length >= MAX_IMAGES_PER_STORY) break;
          if (!chosen.some(item => item.id === image.id)) chosen.push(image);
        }
      }
    } catch (error) { options.log?.push(`${term.term} (${term.kind}): search failed (${error instanceof Error ? error.name : 'error'})`); /* The story keeps its typographic treatment. */ }
  }
  return chosen;
}

/** Keep James's own choices; add the desk's finds without duplicates, within the per-story limit. */
export function mergeImages(existing: LicensedImage[] | undefined, found: LicensedImage[]): LicensedImage[] {
  const merged = [...(existing ?? [])];
  for (const image of found) if (!merged.some(item => item.id === image.id) && merged.length < MAX_IMAGES_PER_STORY + 2) merged.push(image);
  return merged;
}

/** Stories the desk has not yet looked at, newest first. */
export function picturesPending(publications: Publication[], limit: number): Publication[] {
  return publications.filter(publication => publication.mode === 'live' && publication.public && publication.status !== 'removed' && publication.status !== 'retracted' && !publication.picturesCheckedAt)
    .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt)).slice(0, limit);
}
