import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
process.loadEnvFile('.env.local');
const base='https://the-racing-desk.vercel.app';
const anonymous=await fetch(`${base}/api/newsroom`);
assert.equal(anonymous.status,401,'Hosted operator API must reject anonymous requests');
const login=await fetch(`${base}/api/auth`,{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify({password:process.env.ADMIN_PASSWORD}),signal:AbortSignal.timeout(30000)});
assert.equal(login.status,200,'Owner sign-in must work');
const cookie=login.headers.get('set-cookie')?.split(';')[0];
assert.ok(cookie,'Sign-in must issue a session cookie');
const response=await fetch(`${base}/api/newsroom`,{headers:{Cookie:cookie}});
assert.equal(response.status,200);
const initial=await response.json();
const publicResponse=await fetch(`${base}/api/public`);
assert.equal(publicResponse.status,200);
const publicBefore=await publicResponse.json();
assert.equal(publicBefore.contactEmail,'workbenchadmin@gmail.com');
assert.equal(initial.config.contactEmail,'workbenchadmin@gmail.com');
console.log('Hosted auth, persistent storage and public API passed. Public article count:',publicBefore.articles.length);
console.log('Readiness:',initial.config.readiness.map(item=>`${item.name}=${item.ready}`).join('; '));
if(process.argv.includes('--verify-launch')){
  assert.equal(initial.config.monitoring,false);
  assert.equal(initial.config.readiness.find(item=>item.name==='Live research').ready,false);
  const paused=await fetch(`${base}/api/newsroom`,{method:'POST',headers:{'Content-Type':'application/json',Origin:base,Cookie:cookie},body:JSON.stringify({action:'run',mode:'live'}),signal:AbortSignal.timeout(30000)});
  assert.equal(paused.status,503);
  assert.match((await paused.json()).error,/paused at James/);
  const demo=await fetch(`${base}/api/newsroom`,{method:'POST',headers:{'Content-Type':'application/json',Origin:base,Cookie:cookie},body:JSON.stringify({action:'run',mode:'demo'}),signal:AbortSignal.timeout(90000)});
  const result=await demo.json();
  assert.equal(demo.status,200,result.error);
  const waiting=result.state.stories.filter(story=>story.mode==='demo'&&story.status==='waiting_approval');
  assert.ok(waiting.length,'Hosted demo must finish with a reviewable draft');
  const after=await (await fetch(`${base}/api/public`)).json();
  assert.equal(after.articles.length,publicBefore.articles.length);
  const summary={testedAt:new Date().toISOString(),url:base,anonymousStatus:anonymous.status,loginStatus:login.status,publicStatus:publicResponse.status,contactEmail:after.contactEmail,liveAI:'paused by James; no model call',pausedGoStatus:paused.status,demoGoStatus:demo.status,demoDraftsAwaitingApproval:waiting.length,monitoring:false,publicArticles:after.articles.length,automaticEmail:'not connected'};
  writeFileSync('artifacts/launch-verification.json',JSON.stringify(summary,null,2));
  console.log(JSON.stringify(summary,null,2));
}
if(process.argv.includes('--run-live')) {
  const previousAgentRunIds=new Set(initial.state.runs.map(run=>run.id));
  const previousAuditIds=new Set(initial.state.audit.map(entry=>entry.id));
  const operationsBefore=await fetch(`${base}/api/owner/operations`,{headers:{Cookie:cookie}});
  assert.equal(operationsBefore.status,200);
  const previousOperationIds=new Set((await operationsBefore.json()).runs.map(run=>run.id));
  const run=await fetch(`${base}/api/newsroom`,{method:'POST',headers:{'Content-Type':'application/json',Origin:base,Cookie:cookie},body:JSON.stringify({action:'run',mode:'live'}),signal:AbortSignal.timeout(300000)});
  const result=await run.json();
  assert.equal(run.status,200,result.error||'Live GO failed');
  const after=await (await fetch(`${base}/api/public`)).json();
  assert.equal(after.articles.length,publicBefore.articles.length,'GO must never publish');
  assert.equal(result.config.running,false,'GO must release its lease');
  const freshRuns=result.state.runs.filter(item=>!previousAgentRunIds.has(item.id));
  assert.ok(freshRuns.some(item=>item.agentType==='research'&&item.status==='completed'),'A real researcher must complete; HTTP 200 alone is insufficient');
  assert.ok(freshRuns.some(item=>item.agentType==='editorial'&&item.status==='completed'),'A PE editor must complete');
  assert.ok(freshRuns.every(item=>item.status==='completed'),'Fresh agent runs must have no operational failures');
  const freshFailures=result.state.audit.filter(entry=>!previousAuditIds.has(entry.id)&&['editorial.provider_failed','run_failed','research.attempt_failed'].includes(entry.action));
  assert.equal(freshFailures.length,0,'A failed model call or fallback cannot count as an AI success');
  const touchedIds=new Set(freshRuns.map(item=>item.storyId));
  const stories=result.state.stories.filter(story=>story.mode==='live'&&touchedIds.has(story.id));
  assert.ok(stories.some(story=>story.claims.some(claim=>claim.status==='verified')&&story.draft?.sentences.length&&story.proposedDraft?.sentences.length),'Require verified evidence, a safe draft and an actual PE model proposal');
  const operationsResponse=await fetch(`${base}/api/owner/operations`,{headers:{Cookie:cookie}});
  assert.equal(operationsResponse.status,200);
  const operation=(await operationsResponse.json()).runs.find(item=>!previousOperationIds.has(item.id)&&item.mode==='live');
  assert.ok(operation,'The hosted run must have a new durable operations record');
  assert.equal(operation.status,'completed');
  for(const stage of ['preflight','research','editorial'])assert.ok(operation.usage.some(item=>item.stage===stage&&item.inputTokens>0&&item.outputTokens>0),`Require actual ${stage} model usage`);
  const summary={testedAt:new Date().toISOString(),url:base,anonymousStatus:anonymous.status,loginStatus:login.status,goStatus:run.status,stories:result.state.stories.map(story=>({id:story.id,status:story.status,mode:story.mode,claims:story.claims.length,verifiedClaims:story.claims.filter(claim=>claim.status==='verified').length,openGaps:story.gaps.filter(gap=>gap.status==='open').map(gap=>gap.question)})),publicArticles:after.articles.length,failures:result.state.audit.filter(entry=>entry.action.includes('failed')).map(entry=>({action:entry.action,detail:entry.detail}))};
  writeFileSync('artifacts/live-verification.json',JSON.stringify(summary,null,2));
  console.log(JSON.stringify(summary,null,2));
}
