import Link from 'next/link';
import { HeardSomething, PaperFooter, PaperHeader } from '@/components/publication-brand';
import { editionPreview, listEditions } from '@/lib/editions';
import './edition.css';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Edition archive' };
const dateLabel = (date: string) => new Date(`${date}T12:00:00Z`).toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Australia/Sydney' });
export default async function EditionsPage() {
  const editions = await Promise.all((await listEditions()).map(editionPreview));
  return <main className="paper reader-paper"><PaperHeader /><div className="paper-dateline"><span>THE EDITION ARCHIVE</span><span>AUSTRALIAN THOROUGHBRED RACING</span><Link href="/member">Your account ↗</Link></div>
    {editions.length ? <><header className="reader-heading"><p className="paper-kicker">PAST &amp; PRESENT</p><h1>Every Thursday,<br />a fresh perspective.</h1><p>Browse the paper, edition by edition. Each issue brings together the week’s reviewed reporting.</p></header><div className="reader-archive-layout"><div className="reader-archive-list">{editions.map((edition, index) => <article className={`reader-archive-entry ${index === 0 ? 'reader-archive-latest' : ''}`} key={edition.id}><div className="reader-issue-number"><span>No.</span><strong>{edition.number}</strong></div><div><p className="paper-kicker">{index === 0 ? 'LATEST EDITION · ' : ''}<time dateTime={edition.date}>{dateLabel(edition.date)}</time></p><h2><Link href={`/editions/${edition.id}`}>{edition.title}</Link></h2><p>{edition.preview}</p><div className="paper-byline">{edition.articleCount} {edition.articleCount === 1 ? 'story' : 'stories'} in this edition</div><Link className="paper-continue" href={`/editions/${edition.id}`}>Open the edition ↗</Link></div></article>)}</div><aside className="reader-margin"><p className="paper-column-label">THE READING ROOM</p><h2>Your paper.<br />At your pace.</h2><p>Open an edition to see its contents and free introduction. Subscribers can read the complete issue and print a copy.</p><Link className="paper-continue" href="/member">Subscriber sign in ↗</Link><div className="paper-rule" /><h3>Keep the record straight.</h3><p>Corrections and updates remain part of our reporting.</p><Link className="paper-continue" href="/corrections">Corrections &amp; updates ↗</Link></aside></div></> : <section className="paper-opening"><div><p className="paper-kicker">THE EDITION ARCHIVE</p><h1>The record<br />starts here.</h1><p className="paper-deck">The first Thursday Post is being prepared.</p><p>Once the first edition is reviewed and released, it will appear here. Future editions will join it in the permanent archive.</p><Link className="paper-continue" href="/">Return to the front page ↗</Link></div><aside><p className="paper-kicker">BECOME A READER</p><h2>A wider view<br />of racing.</h2><p>People, policy, places and the stories that matter beyond the result.</p><Link className="paper-button" href="/subscribe">Subscription information ↗</Link><div className="paper-rule" /><p>Already registered? <Link href="/member">Sign in to your account.</Link></p></aside></section>}
    <HeardSomething /><PaperFooter /></main>;
}
